# Generated by Django 5.2.3 on 2025-10-13 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin_eventos', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_eve_fecha_hora', models.DateTimeField()),
                ('asi_eve_estado', models.CharField(max_length=45)),
                ('asi_eve_soporte', models.FileField(upload_to='upload/')),
                ('asi_eve_qr', models.ImageField(upload_to='upload/')),
                ('asi_eve_clave', models.CharField(max_length=45)),
                ('asi_eve_asistente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.asistente')),
                ('asi_eve_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.evento')),
            ],
            options={
                'verbose_name': 'Inscripción de Asistente',
                'verbose_name_plural': 'Inscripciones de Asistentes',
                'unique_together': {('asi_eve_asistente_fk', 'asi_eve_evento_fk')},
            },
        ),
    ]
