# Generated by Django 5.2.3 on 2025-12-10 20:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsistenteEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asi_eve_fecha_hora", models.DateTimeField()),
                ("asi_eve_estado", models.CharField(max_length=45)),
                ("asi_eve_soporte", cloudinary.models.CloudinaryField(max_length=255)),
                ("asi_eve_qr", cloudinary.models.CloudinaryField(max_length=255)),
                ("asi_eve_clave", models.CharField(max_length=45)),
            ],
            options={
                "verbose_name": "Inscripción de Asistente",
                "verbose_name_plural": "Inscripciones de Asistentes",
            },
        ),
    ]
