# Generated by Django 5.2.3 on 2025-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_eve_fecha_hora', models.DateTimeField()),
                ('asi_eve_estado', models.CharField(max_length=45)),
                ('asi_eve_soporte', models.FileField(upload_to='upload/')),
                ('asi_eve_qr', models.ImageField(upload_to='upload/')),
                ('asi_eve_clave', models.CharField(max_length=45)),
            ],
        ),
    ]
