# Generated by Django 5.2.3 on 2025-10-12 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin_eventos', '0002_initial'),
        ('app_asistentes', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenteevento',
            name='asi_eve_asistente_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.asistente'),
        ),
        migrations.AddField(
            model_name='asistenteevento',
            name='asi_eve_evento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.evento'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenteevento',
            unique_together={('asi_eve_asistente_fk', 'asi_eve_evento_fk')},
        ),
    ]
