# Generated by Django 5.2.3 on 2025-12-10 04:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_asistentes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistenteevento",
            name="asi_eve_qr",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="asistenteevento",
            name="asi_eve_soporte",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
