# Generated by Django 5.2.3 on 2025-10-13 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin_eventos', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_eve_fecha', models.DateTimeField(auto_now_add=True)),
                ('par_eve_estado', models.CharField(max_length=45)),
                ('par_eve_documentos', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('par_eve_qr', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('par_eve_clave', models.CharField(max_length=45)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('par_eve_es_grupo', models.BooleanField(default=False)),
                ('par_eve_codigo_proyecto', models.CharField(blank=True, max_length=10, null=True)),
                ('par_eve_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.evento')),
                ('par_eve_participante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.participante')),
                ('par_eve_proyecto_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros_proyecto', to='app_participantes.participanteevento')),
            ],
            options={
                'verbose_name': 'Inscripción de Participante',
                'verbose_name_plural': 'Inscripciones de Participantes',
                'unique_together': {('par_eve_participante_fk', 'par_eve_evento_fk')},
            },
        ),
    ]
