# Generated by Django 5.2.3 on 2025-10-12 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_participantes', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='par_eve_participante_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.participante'),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='par_eve_proyecto_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros_proyecto', to='app_participantes.participanteevento'),
        ),
        migrations.AlterUniqueTogether(
            name='participanteevento',
            unique_together={('par_eve_participante_fk', 'par_eve_evento_fk')},
        ),
    ]
