# Generated by Django 5.2.3 on 2025-12-10 04:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_participantes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participanteevento",
            name="par_eve_documentos",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="participanteevento",
            name="par_eve_qr",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
