# Generated by Django 5.2.3 on 2025-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participantes', '0002_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='par_eve_es_grupo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='par_eve_miembros',
            field=models.ManyToManyField(blank=True, related_name='grupos_proyecto', to='app_usuarios.participante'),
        ),
        migrations.AlterField(
            model_name='participanteevento',
            name='par_eve_qr',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
