# Generated by Django 5.2.3 on 2025-08-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participantes', '0003_participanteevento_par_eve_es_grupo_and_more'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participanteevento',
            name='par_eve_miembros',
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='par_eve_codigo_proyecto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='par_eve_lider_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_liderados', to='app_usuarios.participante'),
        ),
    ]
