# Generated by Django 5.2.3 on 2025-08-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participantes', '0004_remove_participanteevento_par_eve_miembros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participanteevento',
            name='par_eve_lider_grupo',
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='par_eve_proyecto_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros_proyecto', to='app_participantes.participanteevento'),
        ),
    ]
