# Generated by Django 5.2.3 on 2025-10-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('are_nombre', models.CharField(max_length=45)),
                ('are_descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri_descripcion', models.CharField(max_length=150)),
                ('cri_peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_nombre', models.CharField(max_length=100)),
                ('eve_descripcion', models.CharField(max_length=520)),
                ('eve_ciudad', models.CharField(max_length=45)),
                ('eve_lugar', models.CharField(max_length=100)),
                ('eve_fecha_inicio', models.DateField()),
                ('eve_fecha_fin', models.DateField()),
                ('eve_estado', models.CharField(max_length=45)),
                ('eve_cancelacion_iniciada', models.DateTimeField(blank=True, null=True)),
                ('eve_imagen', models.ImageField(upload_to='upload/')),
                ('eve_tienecosto', models.CharField(max_length=45)),
                ('eve_capacidad', models.IntegerField()),
                ('eve_programacion', models.FileField(upload_to='upload/')),
                ('eve_informacion_tecnica', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('preinscripcion_habilitada_asistentes', models.BooleanField(default=False)),
                ('preinscripcion_habilitada_participantes', models.BooleanField(default=False)),
                ('preinscripcion_habilitada_evaluadores', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Texto descriptivo para el archivo', max_length=100)),
                ('archivo', models.FileField(upload_to='upload/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nombre', models.CharField(max_length=45)),
                ('cat_descripcion', models.CharField(max_length=400)),
                ('cat_area_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.area')),
            ],
        ),
    ]
