# Generated by Django 5.2.3 on 2025-10-13 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('are_nombre', models.CharField(max_length=45)),
                ('are_descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nombre', models.CharField(max_length=45)),
                ('cat_descripcion', models.CharField(max_length=400)),
                ('cat_area_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.area')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_nombre', models.CharField(max_length=100)),
                ('eve_descripcion', models.CharField(max_length=520)),
                ('eve_ciudad', models.CharField(max_length=45)),
                ('eve_lugar', models.CharField(max_length=100)),
                ('eve_fecha_inicio', models.DateField()),
                ('eve_fecha_fin', models.DateField()),
                ('eve_estado', models.CharField(max_length=45)),
                ('eve_imagen', models.ImageField(upload_to='upload/', verbose_name='Imagen/Logo del Evento')),
                ('eve_tienecosto', models.CharField(max_length=45)),
                ('eve_capacidad', models.IntegerField()),
                ('eve_programacion', models.FileField(upload_to='upload/', verbose_name='Archivo de Programación')),
                ('eve_informacion_tecnica', models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='Información Técnica Opcional')),
                ('preinscripcion_habilitada_asistentes', models.BooleanField(default=False)),
                ('preinscripcion_habilitada_participantes', models.BooleanField(default=False)),
                ('preinscripcion_habilitada_evaluadores', models.BooleanField(default=False)),
                ('eve_administrador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.administradorevento')),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri_descripcion', models.CharField(max_length=150)),
                ('cri_peso', models.FloatField()),
                ('cri_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_cat_categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.categoria')),
                ('eve_cat_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(through='app_admin_eventos.EventoCategoria', to='app_admin_eventos.categoria'),
        ),
        migrations.CreateModel(
            name='MemoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Texto descriptivo para el archivo', max_length=100)),
                ('archivo', models.FileField(upload_to='upload/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias', to='app_admin_eventos.evento')),
            ],
        ),
    ]
