# Generated by Django 5.2.3 on 2025-07-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin_eventos', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eve_administrador_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.administradorevento'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='cri_evento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.evento'),
        ),
        migrations.AddField(
            model_name='eventocategoria',
            name='eve_cat_categoria_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.categoria'),
        ),
        migrations.AddField(
            model_name='eventocategoria',
            name='eve_cat_evento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(through='app_admin_eventos.EventoCategoria', to='app_admin_eventos.categoria'),
        ),
    ]
