# Generated by Django 5.2.3 on 2025-07-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin_eventos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Texto descriptivo para el archivo', max_length=100)),
                ('archivo', models.FileField(upload_to='memorias/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias', to='app_admin_eventos.evento')),
            ],
        ),
    ]
