# Generated by Django 5.2.3 on 2025-12-10 04:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin_eventos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="eve_imagen",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Imagen/Logo del Evento"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="eve_informacion_tecnica",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Información Técnica Opcional",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="eve_programacion",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Archivo de Programación"
            ),
        ),
        migrations.AlterField(
            model_name="memoriaevento",
            name="archivo",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
