# Generated by Django 5.2.3 on 2025-07-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin_eventos', '0003_memoriaevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Certificado de Asistencia', max_length=200)),
                ('subtitulo', models.CharField(blank=True, help_text='Por ejemplo: “Otorgado a”', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificados/logos/')),
                ('firma', models.ImageField(blank=True, help_text='Imagen de la firma digital', null=True, upload_to='certificados/firmas/')),
                ('texto_pie', models.CharField(blank=True, help_text='Texto que va en el pie de página', max_length=300)),
                ('fecha_formato', models.CharField(default='%d de %B de %Y', help_text='Formato de fecha de Python', max_length=50)),
            ],
        ),
    ]
