# Generated by Django 5.2.3 on 2025-12-10 05:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_admin_eventos", "0003_alter_evento_eve_imagen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="eve_programacion",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="programacion"
            ),
        ),
    ]
