# Generated by Django 5.2.3 on 2025-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin_eventos', '0004_certificateconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateConfig',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='preinscripcion_habilitada',
            new_name='preinscripcion_habilitada_asistentes',
        ),
        migrations.AddField(
            model_name='evento',
            name='preinscripcion_habilitada_evaluadores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='preinscripcion_habilitada_participantes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memoriaevento',
            name='archivo',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
