# Generated by Django 5.2.3 on 2025-10-13 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin_eventos', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_valor', models.IntegerField()),
                ('cal_criterio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.criterio')),
                ('cal_evaluador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.evaluador')),
                ('cal_participante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.participante')),
            ],
            options={
                'unique_together': {('cal_evaluador_fk', 'cal_criterio_fk', 'cal_participante_fk')},
            },
        ),
        migrations.CreateModel(
            name='EvaluadorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_eve_fecha_hora', models.DateTimeField(auto_now_add=True, null=True)),
                ('eva_eve_estado', models.CharField(blank=True, max_length=45, null=True)),
                ('eva_eve_qr', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('eva_eve_clave', models.CharField(blank=True, max_length=45, null=True)),
                ('eva_eve_documento', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('eva_eve_evaluador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.evaluador')),
                ('eva_eve_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin_eventos.evento')),
            ],
            options={
                'verbose_name': 'Inscripción de Evaluador',
                'verbose_name_plural': 'Inscripciones de Evaluadores',
                'unique_together': {('eva_eve_evaluador_fk', 'eva_eve_evento_fk')},
            },
        ),
    ]
