# Generated by Django 5.2.3 on 2025-12-10 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_admin_eventos", "0002_initial"),
        ("app_evaluadores", "0001_initial"),
        ("app_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calificacion",
            name="cal_evaluador_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_usuarios.evaluador"
            ),
        ),
        migrations.AddField(
            model_name="calificacion",
            name="cal_participante_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_usuarios.participante",
            ),
        ),
        migrations.AddField(
            model_name="evaluadorevento",
            name="eva_eve_evaluador_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_usuarios.evaluador"
            ),
        ),
        migrations.AddField(
            model_name="evaluadorevento",
            name="eva_eve_evento_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_admin_eventos.evento",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calificacion",
            unique_together={
                ("cal_evaluador_fk", "cal_criterio_fk", "cal_participante_fk")
            },
        ),
        migrations.AlterUniqueTogether(
            name="evaluadorevento",
            unique_together={("eva_eve_evaluador_fk", "eva_eve_evento_fk")},
        ),
    ]
