# Generated by Django 5.2.3 on 2025-12-10 04:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_evaluadores", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluadorevento",
            name="eva_eve_documento",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="documento_evaluador",
            ),
        ),
        migrations.AlterField(
            model_name="evaluadorevento",
            name="eva_eve_qr",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="qr_code"
            ),
        ),
    ]
